export const patientData = [
  {
    id: 1,
    Name: "Salman farooqi ",
    fName: "dilawer khan ",
    department: "cardiology",
    disease: "heart",
    date: "12-7-2001",
    appointmentDate: "17-3-2021",
    action: "test",
  },
  {
    id: 2,
    Name: "abbas khan",
    fName: " jan khan ",
    department: "cardiology",
    disease: "pyschcology",
    date: "12-7-2001",
    appointmentDate: "17-3-2021",
    action: "test",
  },
  {
    id: 3,
    Name: "ihsan khan",
    fName: "akbar khan ",
    department: "cardiology",
    disease: "heart",
    date: "12-7-2001",
    appointmentDate: "17-3-2021",
    action: "test",
  },
  {
    id: 4,
    Name: " farooqi khan",
    fName: "ali khan ",
    department: "cardiology",
    disease: "heart",
    date: "12-7-2001",
    appointmentDate: "17-3-2021",
    action: "test",
  },
  {
    id: 5,
    Name: "afaq hussain",
    fName: "khan akbar ",
    department: "surgry",
    disease: "heart",
    date: "12-7-2001",
    appointmentDate: "17-3-2021",
    action: "test",
  },
  {
    id: 6,
    Name: "afaq hussain",
    fName: "khan ",
    department: "cardiology",
    disease: "heart",
    date: "12-7-2001",
    appointmentDate: "17-3-2021",
    action: "test",
  },
  {
    id: 7,
    Name: "afaq hussain",
    fName: "khan ",
    department: "cardiology",
    disease: "heart",
    date: "12-7-2001",
    appointmentDate: "17-3-2021",
    action: "test",
  },
  {
    id: 8,
    Name: "afaq hussain",
    fName: "khan ",
    department: "cardiology",
    disease: "heart",
    date: "12-7-2001",
    appointmentDate: "17-3-2021",
    action: "test",
  },
  {
    id: 9,
    Name: "afaq hussain",
    fName: "khan ",
    department: "cardiology",
    disease: "heart",
    date: "12-7-2001",
    appointmentDate: "17-3-2021",
    action: "test",
  },
  {
    id: 10,
    Name: "afaq hussain",
    fName: "khan ",
    department: "cardiology",
    disease: "heart",
    date: "12-7-2001",
    appointmentDate: "17-3-2021",
    action: "test",
  },
];
